# Generated by Django 5.2.5 on 2025-08-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement (e.g. kg, l, pcs)", max_length=20
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materials",
                "ordering": ["name"],
            },
        ),
    ]
