# Generated by Django 5.2.5 on 2025-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(
                choices=[("kg", "Kilogram"), ("l", "Liter"), ("pcs", "Piece")],
                help_text="Unit of measurement",
                max_length=10,
            ),
        ),
    ]
