# Generated by Django 5.2.5 on 2025-08-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
        ("plants", "0002_alter_bedsection_options_alter_gardenbed_options_and_more"),
        ("tasks", "0001_initial"),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="gardenbedtask",
            constraint=models.UniqueConstraint(
                fields=("bed", "task"), name="unique_bed_per_task"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialusage",
            constraint=models.UniqueConstraint(
                fields=("task", "material"), name="unique_material_per_task"
            ),
        ),
        migrations.AddConstraint(
            model_name="tasktool",
            constraint=models.UniqueConstraint(
                fields=("task", "tool"), name="unique_tool_per_task"
            ),
        ),
    ]
