# Generated by Django 5.2.5 on 2025-08-27 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bedsection",
            options={
                "ordering": ["bed", "plant"],
                "verbose_name": "Bed Section",
                "verbose_name_plural": "Bed Sections",
            },
        ),
        migrations.AlterModelOptions(
            name="gardenbed",
            options={
                "ordering": ["name"],
                "verbose_name": "Garden bed",
                "verbose_name_plural": "Garden beds",
            },
        ),
        migrations.AlterModelOptions(
            name="plant",
            options={
                "ordering": ["name"],
                "verbose_name": "Plant",
                "verbose_name_plural": "Plants",
            },
        ),
        migrations.AlterField(
            model_name="bedsection",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.1)],
            ),
        ),
        migrations.AlterField(
            model_name="bedsection",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.1)],
            ),
        ),
        migrations.AlterField(
            model_name="gardenbed",
            name="length",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.1)],
            ),
        ),
        migrations.AlterField(
            model_name="gardenbed",
            name="width",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.1)],
            ),
        ),
    ]
