# Generated by Django 5.2.5 on 2025-08-25 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0002_bedsection_length_bedsection_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedsection",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="plants.plant",
            ),
        ),
    ]
