# Generated by Django 5.2.5 on 2025-08-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0003_alter_bedsection_plant"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="plant_type",
            field=models.CharField(
                choices=[
                    ("VEG", "Vegetable"),
                    ("HERB", "Herb"),
                    ("BERRY", "Berry"),
                    ("FLOWER", "Flower"),
                ],
                default="VEG",
                max_length=10,
            ),
        ),
    ]
