# Generated by Django 5.2.5 on 2025-08-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_USE", "In use"),
                            ("BROKEN", "Broken"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("is_checked_out", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
                "ordering": ["name"],
            },
        ),
    ]
